/**
 * 
 */
package com.relaxedcomplexity.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;

/**
 * @author jim.medlock
 *
 */
@Controller
public class SpringHW {

  @RequestMapping("/welcome")
  public ModelAndView helloWorld() {
 
    String message = 
        "<br>" +
        "<div style='text-align:center;'>" +
          "<h3>Hello World</h3>" + 
          "<h3>Welcome to your first Spring MVC Application</h3>" +
          "<p>This message was generated by SpringHW.java</p>" +
        "</div>" +
        "<br><br>";
    return new ModelAndView("welcome", "message", message);
  }
  
}
